<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://environmentaldashboard.org/css/bootstrap.css?v=<?php echo time(); ?>">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v=9ByOqqx0o3">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png?v=9ByOqqx0o3">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png?v=9ByOqqx0o3">
    <link rel="manifest" href="/manifest.json?v=9ByOqqx0o3">
    <link rel="mask-icon" href="/safari-pinned-tab.svg?v=9ByOqqx0o3" color="#00a300">
    <link rel="shortcut icon" href="/favicon.ico?v=9ByOqqx0o3">
    <meta name="theme-color" content="#000000">
    <title>Environmental Dashboard</title>
  </head>
  <body>
    <div class="container">
      <?php include 'includes/header.php'; ?>
      <div class="row" style="padding: 30px">
        <div class="col-12 col-sm-4">
          <h1 class="text-center">Resources Explained</h1>
          <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link active" id="ep-tab" data-toggle="pill" href="#ep" role="tab" aria-controls="ep" aria-selected="true">Electricity Production</a>
            <a class="nav-link" id="dw-tab" data-toggle="pill" href="#dw" role="tab" aria-controls="dw" aria-selected="false">Drinking Water</a>
            <a class="nav-link" id="wa-tab" data-toggle="pill" href="#wa" role="tab" aria-controls="wa" aria-selected="false">Watershed</a>
            <a class="nav-link" id="ww-tab" data-toggle="pill" href="#ww" role="tab" aria-controls="ww" aria-selected="false">Waste Water</a>
            <a class="nav-link" id="weather-tab" data-toggle="pill" href="#weather" role="tab" aria-controls="weather" aria-selected="false">Weather</a>
            <a class="nav-link" id="agriculture-tab" data-toggle="pill" href="#agriculture" role="tab" aria-controls="agriculture" aria-selected="false">Agriculture</a>
            <a class="nav-link" id="urbanization-tab" data-toggle="pill" href="#urbanization" role="tab" aria-controls="urbanization" aria-selected="false">Urbanization and Cleveland</a>
            <a class="nav-link" id="town-tab" data-toggle="pill" href="#town" role="tab" aria-controls="town" aria-selected="false">The Town of Oberlin</a>
            <a class="nav-link" id="college-tab" data-toggle="pill" href="#college" role="tab" aria-controls="college" aria-selected="false">Oberlin College</a>
            <a class="nav-link" id="tappan-tab" data-toggle="pill" href="#tappan" role="tab" aria-controls="tappan" aria-selected="false">Tappan Square</a>
            <a class="nav-link" id="v-pills-profiyou-tab" data-toggle="pill" href="#v-pills-profiyou" role="tab" aria-controls="v-pills-profiyou" aria-selected="false">You!</a>
            <a class="nav-link" id="ref-tab" data-toggle="pill" href="#ref" role="tab" aria-controls="ref" aria-selected="false">References and Notes</a>
          </div>
        </div>
        <div class="col-12 col-sm-8">
          <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="ep" role="tabpanel" aria-labelledby="ep-tab">
              <h4 class="text-center">Electricity Production</h4>
              <img src="http://environmentaldashboard.org/images/uploads/2015/07/1-Electricity-Production1.jpg" alt="" class="img-thumbnail img-fluid">
              <p><span class="firstcharacter">E</span>very time you turn on a light, electricity flows from the source of production to your home, school or business. Oberlin Municipal Light and Power System (OMLPS) is a community-owned, not-for-profit utility founded by Oberlin citizens in 1934 to provide our community with electricity. Although OMLPS has its own generating facility, most of the community’s electricity is produced outside of Oberlin. Electricity for Oberlin is generated using a mixture of energy sources. In 2014 these include landfill gas (56%), coal (22%), hydroelectric (10%), wind (3%), solar (3%), nuclear (4%) and natural gas (2%)<sup>1</sup>.</p>
              <p>Generating electricity with fossil fuels produces greenhouse gas emissions that result in climate change. In 2007, a little over half of total greenhouse gas emissions in City of Oberlin resulted from electricity generation and the rest came mostly from gasoline and diesel used for transportation and natural gas used for heating<sup>2</sup>. The City has committed to climate neutrality by 2050, a condition in which the community is no longer responsible for contributing to an overall increase in greenhouse gasses. To fulfill this commitment the city has made additional contractual commitments to obtain electricity from landfill gas, hydroelectric, solar and wind; by 2015 Oberlin is slated to receive 90% of its electricity through renewable/climate-neutral electricity<sup>3</sup>. For electricity, transportation and heating, choosing to use less energy (e.g. by turning lights off and walking) and upgrading to more efficient technology (e.g. by using LED lights) are among the most important actions that consumers can take to benefit the environment.</p>
            </div>
            <div class="tab-pane fade" id="dw" role="tabpanel" aria-labelledby="dw-tab">
              <h4 class="text-center">Drinking Water</h4>
              <img src="http://environmentaldashboard.org/images/uploads/2015/07/2-Drinking-Water1.jpg" alt="" class="img-fluid img-thumbnail">
              <p><span class="firstcharacter">W</span>henever we turn the knob on a faucet or use a washing machine we are consuming water that ultimately comes from the west branch of the Black River. Oberlin has operated a water supply system since 1874: the water is first stored in a reservoir on Parson’s road and then purified by Oberlin’s Drinking Water Treatment Plant. Filtration and chemical processes are used to remove undesirable materials and pathogens. Fluoride is added to reduce tooth decay. An on-site laboratory and monitoring system are used to continuously assess and ensure water quality. The two storage towers that are used to maintain a pressurized water supply are prominent features of Oberlin’s skyline. Cleaned water is pumped from the plant to these towers and then flows directly to our homes and businesses. Oberlin’s plant can treat over two million gallons per day (240 gallons per resident).</p>
              <p>Cleaning and moving water requires energy that results in the release of greenhouse gasses; in combination Oberlin’s drinking and wastewater facilities are responsible for a third of municipal greenhouse gas emissions. This means that even in our water-rich region of the country, water conservation is important for the environment. Water that falls on any of the land upstream from the pumping station becomes our drinking water; it is therefore critical that we protect this watershed, particularly the riparian zone - the area immediately adjacent to the river - to preserve this critical resource.<br></p>
            </div>
            <div class="tab-pane fade" id="wa" role="tabpanel" aria-labelledby="wa-tab">
              <h4 class="text-center">Watershed</h4>
              <img src="http://environmentaldashboard.org/images/uploads/2015/07/3-Watershed1.jpg" alt="" class="img-thumbnail img-fluid">
              <p><span class="firstcharacter">O</span>berlin is located within the Black River Watershed. A watershed is an area of land that drains to a single body of water. For example, Plum Creek’s watershed includes more than 50 square miles of land within and around the City of Oberlin that drain into it. Small watersheds exist inside of larger watersheds; Plum Creek is one of the many smaller tributaries that drain to the Black River, which flows into Lake Erie, which drains into the Saint Lawrence river (at Niagara Falls) and finally into the Atlantic Ocean. The Black River Watershed is biologically diverse in plant species and aquatic life and is home to a variety of wildlife. Excess fertilizers, pesticides and soil particles as well as harmful materials that pass down storm drains negatively affect water quality. As a result of these threats, the Environmental Protection Agency lists the Black River as an “Area of Concern”.</p>
              <p>Next time you cross Plum Creek, notice the flow and color of the water; the coffee color often seen after a rainstorm is caused by soil that has eroded off of upstream farmlands. Almost everything we do in our home and community – fertilizing lawns, agriculture, water use, development and transportation – affects the health of Plum Creek, the Black River and Lake Erie. Oberlin’s drinking water comes from the west branch of the Black River, while our wastewater drains into Plum Creek which empties into the east branch of the Black River. Many regions (including New Russia Township which surrounds Oberlin) obtain drinking water directly from Lake Erie. The choices we make in our homes (and watershed) have important consequences for critical water resources on which we depend!<br></p>
            </div>
            <div class="tab-pane fade" id="ww" role="tabpanel" aria-labelledby="ww-tab">
              <h4 class="text-center">Waste Water</h4>
              <img src="http://environmentaldashboard.org/images/uploads/2015/07/4-Waste-Water1.jpg" alt="" class="img-fluid img-thumbnail">
              <p><span class="firstcharacter">M</span>ost of us don’t think about where the water trickling off our hands or flushed down the toilet ends up after it goes down the drain. The reality is that every building in Oberlin is connected through a series of underground pipes that drain to Oberlin’s wastewater treatment facility on East Lorain Street. Oberlin’s “Water Environmental Protection Facility” is designed to process up to 5.5 million gallons of water per day<sup>5</sup>. Both physical and biological processes are used to clean water so that it meets day specified limits set by the U.S. EPA. During storms, water infiltrates the wastewater pipes in town and excess water reaching the plant is temporarily pumped to a storage basin for later treatment. Once cleaned, treated wastewater is subjected to ultraviolet sterilization and then discharged into the Plum Creek. Composted “sludge”, produced as a byproduct of treatment, is provided as a free nutrient-rich fertilizer to local farmers. The water released from the water treatment plant is actually cleaner than the water already in Plum Creek!<br></p>
            </div>
            <div class="tab-pane fade" id="weather" role="tabpanel" aria-labelledby="weather-tab">
              <h4 class="text-center">Weather</h4>
              <img src="http://environmentaldashboard.org/images/uploads/2015/07/05-Weather1.jpg" alt="" class="img-thumbnail img-fluid">
              <p><span class="firstcharacter">"W</span>eather” describes patterns in temperature, humidity, rainfall and cloud cover over relatively short periods of time, like hours, days or weeks. “Climate”, on the other hand describes patterns in these atmospheric conditions over years, decades and centuries. Oberlin’s location in the temperate zone results in strong seasonal changes in things like availability of local fruits and vegetables and recreational opportunities (swimming, boating, ice fishing, etc.). Lake Erie influences our local climate - we have milder summers and winters and more rain, snow and cloud cover in the winter then areas of the same latitude that are not downwind from a big lake. Oberlin averages about 36 inches of precipitation annually, which includes rain, sleet, and snow.</p>
              <p>Like all regions of the globe, Northeast Ohio’s climate and weather are changing as a result of human activities that produce greenhouse gasses. For example, wetter springs, hotter and drier summers and more intense storms will change the foods we can grow as well as recreational opportunities. Climate also determines renewable energy resources such as wind, solar and hydroelectric. We can be proud of the fact that Oberlin’s increasing reliance on renewable energy is decreasing this community’s contribution to climate change.<br></p>
            </div>
            <div class="tab-pane fade" id="agriculture" role="tabpanel" aria-labelledby="agriculture-tab">
              <h4 class="text-center">Agriculture</h4>
              <img src="http://environmentaldashboard.org/images/uploads/2015/07/06-Agriculture1.jpg" alt="" class="img-thumbnail img-fluid">
              <p><span class="firstcharacter">A</span>griculture is part of the heritage (and future) of Northeast Ohio. The Native Americans who lived in this region began farming corn and beans and squash about 2,000 years ago<sup>6</sup>. When settlers from New England arrived in the early 1800s they found a landscape dominated by forested wetlands. They cut down the trees and buried extensive piping made out of round clay “tiles” to drain the water table and make it more suitable for agriculture. Corn and beans remain the dominant commercial crops in our landscape, but are largely sold as animal feed and as inputs for industrial food production and ethanol used in gasoline. Contemporary agriculture poses a number of environmental challenges including soil erosion, dependence on fossil fuels and water pollution from pesticides and fertilizer use.</p>
              <p>A positive recent development is the increased availability of local fruits, vegetables, dairy products and meats, often sold in farmers markets and through community supported agriculture, and often produced using more sustainable methods. Oberlin’s Farmer’s Market and “City Fresh” feature a diversity of tasty vegetables, fruits, cheeses, bakery items and meats that can’t be found in grocery stores. Buying food from local farmers supports the local economy and can reduce energy use and pollution.<br></p>
            </div>
            <div class="tab-pane fade" id="urbanization" role="tabpanel" aria-labelledby="urbanization-tab">
              <h4 class="text-center">Urbanization and Cleveland</h4>
              <img src="http://environmentaldashboard.org/images/uploads/2015/07/07-Urbanization-and-Cleveland1.jpg" alt="" class="img-thumbnail img-fluid">
              <p><span class="firstcharacter">T</span>he bigger cities around Oberlin such as Elyria, Lorain and Cleveland are part of the “Rust Belt” – places that flourished and then experienced economic decline together with the steel industry. Located on the southern shore of Lake Erie at the mouth of the Cuyahoga River, Cleveland has played an important historical role in the environment. The Cuyahoga was once so polluted with industrial waste that it regularly caught on fire! A 1969 fire attracted so much national attention that it helped inspire landmark environmental legislation, including The Clean Water Act, and the creation of the Environmental Protection Agency (EPA)<sup>7</sup>. A positive result is that the Cuyahoga is much, much cleaner today. However, the Cuyahoga and Lake Erie are still listed as an Area of Concern by the EPA.</p>
              <p>Migration to suburbs has also been a challenge for Cleveland and surrounding rural areas; while regional population has remained fairly constant, Cleveland’s metropolitan population has shrunk dramatically as farm fields in the region have been converted to houses. Innovative efforts underway to sustainably re-develop Cleveland include urban parks, urban agriculture, increased ties to farms in the surrounding landscape, public transit equipped with bicycle carriers and plans for large scale wind farms on the coast. Visit the “<a href="http://www.gcbl.org/">Green City Blue Lake</a>” website for more information on Cleveland and region solutions.</p>
            </div>
            <div class="tab-pane fade" id="town" role="tabpanel" aria-labelledby="town-tab">
              <h4 class="text-center">The Town of Oberlin</h4>
              <img src="http://environmentaldashboard.org/images/uploads/2015/07/08-The-Town-of-Oberlin1.jpg" alt="" class="img-thumbnail img-fluid">
              <p><span class="firstcharacter">T</span>wo Christian missionaries founded both the city and college of Oberlin in 1833. The pastor John Frederick Oberlin, after whom the town and college were aptly named, lived a life of service to the poor in the Alsatian region of France where he promoted public education, advances in agriculture and the development of town infrastructure, such as sanitation, transportation and health care<sup>8</sup>. Oberlin has grown to approximately 5,000 permanent residents and 3,000 college students. It has a history of leadership on issues of civil rights and justice; during slavery days it was the one of the most prominent stops on the Underground Railroad and many former slaves stayed to become members of the community.</p>
              <p>Oberlin continues to act with a sense of social responsibility; the town and college have jointly committed to environmental sustainability. As a member of Local Governments for Sustainability, the City has committed to climate neutrality by 2050. As a charter signatory of the ACUPCC, Oberlin College committed to climate neutrality by 2025. The community is also home to the “Oberlin Project”, an effort to develop a resilient and prosperous model of a post-fossil fuel economy and culture.<br></p>
            </div>
            <div class="tab-pane fade" id="college" role="tabpanel" aria-labelledby="college-tab">
              <h4 class="text-center">Oberlin College</h4>
              <img src="http://environmentaldashboard.org/images/uploads/2015/07/09-Oberlin-College1.jpg" alt="" class="img-thumbnail img-fluid">
              <p><span class="firstcharacter">O</span>berlin was the first college in the U.S. to regularly admit female and black students. Since its founding students, faculty and alumni of Oberlin have maintained this history of social engagement and responsibility through leadership in anti-slavery, women’s rights, gay rights, labor rights and anti-war movements.</p>
              <p>Oberlin developed its Environmental Studies Program in 1979. Completed in 2000, Oberlin’s award winning Adam Joseph Lewis Center for Environmental Studies<sup>9</sup> relies principally on solar energy and internally recycles water through a wetland-based treatment system. In 2003 Oberlin was one if its first peer institutions to adopt a comprehensive environmental policy and subsequently integrated “move toward environmental sustainability” as one of the pillars of its strategic plan. The policy is revised and managed by the college’s Committee on Environmental Sustainability and by its Office of Environmental Sustainability. In 2007, as one of seven charter member of the ACUPCC, Oberlin College was the first of its peer institutions to commit to carbon neutrality. In 2012 Oberlin College installed a 10 acre, 2.3 mW solar generation facility that provides 12% of its annual electricity needs. The college will soon replace its coal-fired central heating plant, which will be a major additional milestone towards achieving its environmental goals.</p>
              <p>Oberlin developed the first “campus resource monitoring system” which provides students with real-time feedback on water and electricity consumption in its dorms. Through a grant from the Great Lakes Protection Fund, Environmental Dashboard extends this work into the city. Students and faculty members stand committed to continue the tradition of strong environmental stewardship at Oberlin College.</p>
            </div>
            <div class="tab-pane fade" id="tappan" role="tabpanel" aria-labelledby="tappan-tab">
              <h4 class="text-center">Tappan Square</h4>
              <img src="http://environmentaldashboard.org/images/uploads/2015/07/10-Tappan-Square1.jpg" alt="" class="img-thumbnail img-fluid">
              <p><span class="firstcharacter">T</span>appan Square is a 13-acre green space that sits at the heart of the City of Oberlin and provides a gathering place for college students and community members alike. According to legend, the two ministers who founded Oberlin stopped at an elm at the southeast corner to pray and decided to build their community on this spot<sup>10</sup>. The square is named after Arthur Tappan, a 19th-century anti-slavery activist who was instrumental in keeping the college financially solvent in its early years. Oberlin’s first settler, Peter Pinder Pease, built his cabin in what is now the square. Several of the colleges original buildings were also located here, but were removed at the request of ALCOA Aluminum founder and Oberlin alumni, Charles Martin Hall, who funded the conversion to open space in his will.</p>
              <p>A diversity of cultural events are hosted in the square each year including the Big Parade, Juneteenth, the folk festival, the “Doggie Doo” dog parade, the easter egg hunt, the local foods festival, and the summer concert series. Throughout its history, the square has also served as a venue for peaceful demonstrations and political rallies. Having a green space at its core helps to connect the community to each other and to the natural environment. Although many of the trees are local to Ohio, the square reportedly contains trees native to every state in the Union. The square is also home to the famous albino squirrels that call Oberlin home. Join these squirrels in exploring the many sycamores, oaks, and maples that cover the Square.<br></p>
            </div>
            <div class="tab-pane fade" id="you" role="tabpanel" aria-labelledby="you-tab">
              <h4 class="text-center">You!</h4>
              <img src="http://environmentaldashboard.org/images/uploads/2015/07/11-YOU1.jpg" alt="" class="img-thumbnail img-fluid">
              <p><span class="firstcharacter">T</span>he decisions each of us make every day in our home, school and workplace directly affect our community and environment. A few statistics clarify why what we do in buildings is important<sup>11</sup>: North Americans spend over 90% of our lives indoors. Activities that take place in buildings in the U.S. account for 2/3 of our electricity consumption, 1/3 of total energy consumption, 1/3 of U.S. greenhouse gas emissions, 12% of our fresh water consumption and 9% of global greenhouse gas emissions!</p>
              <p>Our hope is that Environmental Dashboard helps citizens gain a better understanding of how choices we make affect the local regional and global environment. Environmental Dashboard highlights the things community members are doing to build a more sustainable and resilient community. The many creative ways that you can conserve and create resources include: turning off lights, taking shorter showers, insulating your home, growing fruits and vegetables in your backyard (or in one of Oberlin’s community gardens), sharing ideas with your neighbors, purchasing from local farms and locally owned businesses, engaging in community decision-making and supporting leaders in local and national government who work towards environmental sustainability.</p>
            </div>
            <div class="tab-pane fade" id="ref" role="tabpanel" aria-labelledby="ref-tab">
              <h4 class="text-center">References and Notes</h4>
              <ol class="references">
                <li id="ref1">Personal communication from Steve Dupee, Electric Director of Oberlin Municipal Light and Power, to John Petersen</li>
                <li id="ref2">Meyers 2009, Baseline greenhouse gas inventory for Oberlin: Stepping up to the challenge of climate neutrality, a report commissioned by City of Oberlin prepare for City of Oberlin Greenhouse Gas Inventory</li>
                <li id="ref3">Personal communication from Steve Dupee, Electric Director of Oberlin Municipal Light and Power, to John Petersen</li>
                <li id="ref4"><a href="http://www.cityofoberlin.com/PublicWorks/WaterDivision.page">www.cityofoberlin.com/PublicWorks/WaterDivision.page</a></li>
                <li id="ref5"><a href="http://www.cityofoberlin.com/PublicWorks/WastewaterDivision.page">www.cityofoberlin.com/PublicWorks/WastewaterDivision.page</a></li>
                <li id="ref6">T. Sherman, 1997, A Place on the glacial till: Time, land and nature within an American town, Oxford press.</li>
                <li id="ref7"><a href="http://www.epa.gov/grtlakes/aoc/cuyahoga.html">www.epa.gov/grtlakes/aoc/cuyahoga.html</a></li>
                <li id="ref8"><a href="http://www.oberlinheritage.org/researchlearn/historyfaqs">www.oberlinheritage.org/researchlearn/historyfaqs</a></li>
                <li id="ref9">Most important green building constructed in the last 30 years (July 2010), Architect Magazine; One of the 30 Milestone Buildings of the 20th Century, U.S. Department of Energy, William McDonough &amp; Partners One of the Top 10 Green Projects (2002), American Institute of Architects (AIA); Build America Award (2001), National Convention of the Associated Contractors of America, Mosser Construction; Build Ohio Award (2000), Associated Contractors of Ohio, Mosser Construction; Honor Award (1999), AIA Committee on Architecture and Education, William McDonough &amp; Partners American Architecture Award (1999), Chicago Anthaeum, William McDonough &amp; Partners</li>
                <li id="ref10"><a href="http://new.oberlin.edu/student-life/facilities/detail.dot?id=30308&amp;buildingId=30214">new.oberlin.edu/student-life/facilities/detail.dot?id=30308&amp;buildingId=30214</a></li>
                <li id="ref11"><a href="http://www.epa.gov/greenbuilding/pubs/gbstats.pdf">www.epa.gov/greenbuilding/pubs/gbstats.pdf</a></li>
                </ol>
            </div>
          </div>
        </div>
      </div>
      <?php include 'includes/footer.php'; ?>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>