<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://environmentaldashboard.org/css/bootstrap.css?v=<?php echo time(); ?>">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v=9ByOqqx0o3">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png?v=9ByOqqx0o3">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png?v=9ByOqqx0o3">
    <link rel="manifest" href="/manifest.json?v=9ByOqqx0o3">
    <link rel="mask-icon" href="/safari-pinned-tab.svg?v=9ByOqqx0o3" color="#00a300">
    <link rel="shortcut icon" href="/favicon.ico?v=9ByOqqx0o3">
    <meta name="theme-color" content="#000000">
    <title>Environmental Dashboard</title>
  </head>
  <body>
    <div class="container">
      <?php include '../includes/header.php'; ?>
      <div class="row">
        <div class="col-12">
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img class="d-block w-100" src="/images/uploads/2016/10/Instructortoolkitslide1.jpg" alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                  <h3 style="color: #fff">Higher Ed. Teaching Tools</h5>
                </div>
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="/images/uploads/2015/10/Splashimageteacherresourcespage.jpg" alt="K-12 Education Teaching Tools">
                <div class="carousel-caption d-none d-md-block">
                  <h3 style="color: #fff">K-12 Education Teaching</h5>
                </div>
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="/images/uploads/2015/11/Splashimageteacherresource2.jpg" alt="Supporting Resources">
                <div class="carousel-caption d-none d-md-block">
                  <h3 style="color: #fff">Supporting Resources</h5>
                </div>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
      </div>
      <div class="row" style="padding: 30px">
        <div class="col-12">
          <h2>WHAT, WHY, HOW</h2>
          <h3>What are the aims of the Dashboard educational tools?</h3>
          <p>We believe that students are powerful agents of change. Dashboard lesson plans build on curricular standards and help students become better systems thinkers. In helping students to gain a better understanding of their roles in their communities, we aim for Dashboard lesson plans to engage and empower students in pro-environmental thought and action.</p>
          <h3>Why are Dashboard educational tools unique?</h3>
          <p>Dashboard lesson plans are real and relevant to students because they incorporate data and stories that are unique to their own lives. Building Dashboard lesson plans center around real data generated by the students themselves. Community Voices lesson plans engage students in the power speech in their communities to motivate and empower pro-environmental thought and action.</p>
          <h3>How to navigate this portion of the website:</h3>
          <p>We have two databases at your disposal. Dashboard lesson plans are lessons that directly use the Dashboard as a teaching tool. In addition, we’ve found resources that do not directly use the Dashboard, but might be helpful in teaching a Dashboard class/lesson. These resources are included in the Supporting Resources database. You’ll be able to easily navigate between these databases because each Dashboard lesson plan is also linked to specific supporting resources that we think might be helpful.</p>
          <h3>Select Education Level to Search</h3>
        </div>
      </div>
      <div class="row" style="padding: 30px">
        <div class="col-6 text-center"><a href="/edresources/searchedresources"><img src="/images/uploads/2016/10/K12Icon.jpg" alt="" class="img-fluid" width="50%"></a></div>
      </div>
      <div class="row">
        <div class="col-12" style="padding: 30px">
        </div>
      </div>
      <?php require '../includes/footer.php'; ?>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>