<!doctype html>
<html lang="en">
  <head>
    <meta name="description" content="Search our repository of Dashboard lesson plans that build on curricular standards and help students become better systems thinkers. Lessons use real data generated by students themselves and engage students in the power of speech to motivate pro-environmental thought and action.">
    <?php include '../includes/html-head.php'; ?>
  </head>
  <body>
    <?php include '../includes/header.php'; ?>
    <div class="container p-0">
      <div class="row">
        <div class="col-12">
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img class="d-block w-100" src="/images/uploads/2016/10/Instructortoolkitslide1.jpg" alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                  <h3 style="color: #fff">Higher Ed. Teaching Tools</h5>
                </div>
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="/images/uploads/2015/10/Splashimageteacherresourcespage.jpg" alt="K-12 Education Teaching Tools">
                <div class="carousel-caption d-none d-md-block">
                  <h3 style="color: #fff">K-12 Education Teaching</h5>
                </div>
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="/images/uploads/2015/11/Splashimageteacherresource2.jpg" alt="Supporting Resources">
                <div class="carousel-caption d-none d-md-block">
                  <h3 style="color: #fff">Supporting Resources</h5>
                </div>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
      </div>
      <div class="row" style="padding: 30px">
        <div class="col-12">
          <h2 class="text-left primary-heading">WHAT, WHY, HOW</h2>
          <h3 class="text-left primary-heading">What are the aims of the Dashboard-related lessons?</h3>
          <p>We believe that students can be powerful agents of change. Dashboard related lessons are designed to engage, motivate and empower students to improve their community and their environment while they develop systems thinking skills and core competencies.</p>
          <h3 class="text-left primary-heading">Why are Dashboard educational tools unique?</h3>
          <p>Building Dashboard, Citywide Dashboard and BuildingOS use real-time data on the environmental performance of buildings to engage students in authentic research; these tools compel students to ask and answer important questions for which answers are not already known.  It empowers them to identify how behavior and management choices influence resource use and environmental impacts.  Community Voices-related lessons empower students to promote pro-environmental and pro-community thought and action.</p>
          <h3 class="text-left primary-heading">How to navigate this portion of the website:</h3>
          <p>Click the search button below to search the expanding repository of lessons developed by educators in K-college who are using Environmental Dashboard to empower their students.</p>
        </div>
      </div>
      <div class="row" style="padding: 30px">
        <div class="col text-center">
          <a href="<?=$generateURL("edresources/searchedresources")?>" class="btn btn-lg btn-primary">
            Search
          </a>
        </div>
      </div>
      <div class="row">
        <div class="col-12" style="padding: 30px">
        </div>
      </div>
      <?php require '../includes/footer.php'; ?>
    </div>
    <?php include '../includes/js.php'; ?>
  </body>
</html>